server:
  port: 8080
  use-forwarded-headers: true
#redis:
#  om:
#    spring:
#      repository:
#        query:
#          limit: 10000

spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
