server:
  port: 8080
  use-forwarded-headers: true
#redis:
#  om:
#    spring:
#      repository:
#        query:
#          limit: 10000

#spring:
#  data:
#    redis:
#      database: 0
#      host: 10.125.135.117 #localhost
#      port: 6379
      #cluster:
      #  nodes: localhost:6379

spring:
  redis:
    host: 10.125.135.117
    port: 6379
    ssl: false
    cluster:
      enabled: false